@Leaderboard.Api_HostAddress = https://localhost:32773

POST {{Leaderboard.Api_HostAddress}}/customer/3/score/50
Accept: application/json
###


GET {{Leaderboard.Api_HostAddress}}/leaderboard?start=1&end=10
Accept: application/json
###


GET {{Leaderboard.Api_HostAddress}}/leaderboard/2?high=1&low=1
Accept: application/json

###